import type { Metadata } from "next";
import {
  Bubblegum_Sans,
  Geist,
  Geist_Mono,
  Henny_Penny,
  Outfit,
} from "next/font/google";
import { GameSocketProvider } from "@/context/GameSocketContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bubblegumSans = Bubblegum_Sans({
  variable: "--font-bubblegum-sans",
  subsets: ["latin"],
  weight: "400",
});

const hennyPenny = Henny_Penny({
  variable: "--font-henny-penny-family",
  subsets: ["latin"],
  weight: "400",
});

const outfit = Outfit({
  variable: "--font-outfit-family",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bubblegumSans.variable} ${hennyPenny.variable} ${outfit.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GameSocketProvider>{children}</GameSocketProvider>
      </body>
    </html>
  );
}
